name = "BedSync"
client_id = "b7ed18e946c3ca173a256dc62a5d7750"
application_url = "https://bedsync.net"
embedded = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://bedsync.net/api/auth/callback"]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/api/webhooks/shopify"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/api/webhooks/shopify"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/api/webhooks/shopify"
